---
# Copyright 2016, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Create LXC cache dir
  file:
    path: "{{ cache_path_fact }}"
    state: "directory"
    recurse: true

- name: Remove existing cache archive
  file:
    path: "{{ cache_path_fact }}/rootfs.tar.xz"
    state: "absent"

# This is using a shell command because the ansible archive module does not
# provide for the options needed to properly create an LXC image archive.
# Ansible will print a warning since this task calls 'tar' directly and we
# suppress this warning with 'warn: no'.
- name: Create lxc image
  shell: |
    tar -Opc -C {{ lxc_image_cache_path }} . | {{ lxc_xz_bin }} -T 0 -{{ lxc_image_compression_ratio }} -c - > rootfs.tar.xz
  args:
    chdir: "{{ cache_path_fact }}/"
    warn: no
  tags:
    - skip_ansible_lint

- name: Fetch LXC image-metadata
  shell: >
    aria2c
    --max-connection-per-server=4
    --continue
    --allow-overwrite=true
    --dir=/tmp
    --out=meta.tar.xz
    --check-certificate={{ (lxc_hosts_validate_certs | bool) | lower }}
    {% for server in lxc_image_cache_server_mirrors %}{{ server }}/{{ item.split(';')[-1] }}/meta.tar.xz {% endfor %}
  args:
    warn: no
  with_items:
    - "{{ lxc_images }}"
  tags:
    - skip_ansible_lint
    - always

- name: Place container metadata
  unarchive:
    src: "/tmp/meta.tar.xz"
    dest: "{{ cache_path_fact }}"
    remote_src: True
  notify:
    - Remove metadata archive

- name: Set cache expiry
  shell: "date -d @{{ (cache_time | int) + 31536000 }}"
  changed_when: false
  register: _cache_expiry
  tags:
    - skip_ansible_lint

- name: Set expiry
  copy:
    content: "{{ _cache_expiry.stdout }}"
    dest: "{{ cache_path_fact }}/expiry"

- name: Set build ID
  copy:
    content: "{{ cache_time }}"
    dest: "{{ cache_path_fact }}/build_id"

- include: "{{ item }}"
  static: no
  with_first_found:
    - files:
        - "lxc_container_{{ lxc_container_backing_store | default('None') }}.yml"
      skip: true
